<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HW1315" name="Grouping(failed)" tests="77" failures="35" timestamp="3 Feb 2017 12:42:32 GMT" time="21240.443" errors="0">
  <testcase name="TC139_Design_Project_Sub_Page_Template_Pa" time="276.438" classname="com.desktopWeb.scripts.sprint1.TC_139_Design_Project_Sub_Page_Template_Pa">
    <failure type="java.lang.AssertionError" message="Step TC139_Design_Project_Sub_Page_Template_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC139_Design_Project_Sub_Page_Template_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_139_Design_Project_Sub_Page_Template_Pa.TC139_Design_Project_Sub_Page_Template_Pa(TC_139_Design_Project_Sub_Page_Template_Pa.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC139_Design_Project_Sub_Page_Template_Pa -->
  <testcase name="TC124_Verify_Project_Sub_Page_Delete_En" time="74.663" classname="com.desktopWeb.scripts.sprint1.TC_124_Verify_Project_Sub_Page_Delete_En"/>
  <testcase name="TC82_Verify_Site_Sub_Page_Version_Approve" time="113.471" classname="com.desktopWeb.scripts.page.TC_82_Verify_Site_Sub_Page_Version_Approve"/>
  <testcase name="TC140_SEO_Project_Sub_Page_Name_Pa" time="271.807" classname="com.desktopWeb.scripts.sprint1.TC_140_SEO_Project_Sub_Page_Name_Pa">
    <failure type="java.lang.AssertionError" message="Step TC140_SEO_Project_Sub_Page_Name_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC140_SEO_Project_Sub_Page_Name_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_140_SEO_Project_Sub_Page_Name_Pa.TC140_SEO_Project_Sub_Page_Name_Pa(TC_140_SEO_Project_Sub_Page_Name_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC140_SEO_Project_Sub_Page_Name_Pa -->
  <testcase name="TC148_Verify_Page_News_Page_Version_Duplicate_En" time="375.879" classname="com.desktopWeb.scripts.sprint1.TC_148_Verify_Page_News_Page_Version_Duplicate_En">
    <failure type="java.lang.AssertionError" message="Step TC148_Verify_Page_News_Page_Version_Duplicate_En Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC148_Verify_Page_News_Page_Version_Duplicate_En Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_148_Verify_Page_News_Page_Version_Duplicate_En.TC148_Verify_Page_News_Page_Version_Duplicate_En(TC_148_Verify_Page_News_Page_Version_Duplicate_En.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC148_Verify_Page_News_Page_Version_Duplicate_En -->
  <testcase name="TC138_Verify_Project_Sub_Page_Delete_Pa" time="67.872" classname="com.desktopWeb.scripts.sprint1.TC_138_Verify_Project_Sub_Page_Delete_Pa"/>
  <testcase name="TC86_Verify_Page_News_Page_Delete" time="149.105" classname="com.desktopWeb.scripts.page.TC_86_Verify_Page_News_Page_Delete"/>
  <testcase name="TC167_Verify_Page_News_Page_Version_NewPage_Pa" time="367.641" classname="com.desktopWeb.scripts.sprint1.TC_167_Verify_Page_News_Page_Version_NewPage_Pa">
    <failure type="java.lang.AssertionError" message="Step TC167_Verify_Page_News_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC167_Verify_Page_News_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_167_Verify_Page_News_Page_Version_NewPage_Pa.TC167_Verify_Page_News_Page_Version_NewPage_Pa(TC_167_Verify_Page_News_Page_Version_NewPage_Pa.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC167_Verify_Page_News_Page_Version_NewPage_Pa -->
  <testcase name="TC156_Design_Page_News_Page_Template_Cm" time="204.251" classname="com.desktopWeb.scripts.sprint1.TC_156_Design_Page_News_Page_Template_Cm"/>
  <testcase name="TC166_Design_Page_News_Page_Template_Pa" time="395.961" classname="com.desktopWeb.scripts.sprint1.TC_166_Design_Page_News_Page_Template_Pa">
    <failure type="java.lang.AssertionError" message="Step TC166_Design_Page_News_Page_Template_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC166_Design_Page_News_Page_Template_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_166_Design_Page_News_Page_Template_Pa.TC166_Design_Page_News_Page_Template_Pa(TC_166_Design_Page_News_Page_Template_Pa.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC166_Design_Page_News_Page_Template_Pa -->
  <testcase name="TC79_Location_Site_Sub_Page_Location" time="295.026" classname="com.desktopWeb.scripts.page.TC_79_Location_Site_Sub_Page_Location"/>
  <testcase name="TC174_Verify_Field_Enable_ToEdit_Dashoard_Project_En" time="246.75" classname="com.desktopWeb.scripts.sprint2.TC_174_Verify_Field_Enable_ToEdit_Dashoard_Project_En">
    <failure type="java.lang.AssertionError" message="Step IsEnabled  Failed with description Project Type is not Enabled expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step IsEnabled  Failed with description Project Type is not Enabled expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.isEnabled(ActionEngine.java:1161)
	at com.desktopWeb.workflows.HelperClass.VerifyFieldsEnableToEditOnProjectPage(HelperClass.java:2331)
	at com.desktopWeb.scripts.sprint2.TC_174_Verify_Field_Enable_ToEdit_Dashoard_Project_En.TC174_Verify_Field_Enable_ToEdit_Dashoard_Project_En(TC_174_Verify_Field_Enable_ToEdit_Dashoard_Project_En.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC174_Verify_Field_Enable_ToEdit_Dashoard_Project_En -->
  <testcase name="TC129_Verify_Project_Sub_Page_Delete_Cm" time="192.854" classname="com.desktopWeb.scripts.sprint1.TC_129_Verify_Project_Sub_Page_Delete_Cm"/>
  <testcase name="TC173_Detail_Project_Dashboard_Project_SiteAdmin" time="408.973" classname="com.desktopWeb.scripts.sprint2.TC_173_Detail_Project_Dashboard_Project_SiteAdmin">
    <failure type="java.lang.AssertionError" message="Step TC173_Detail_Project_Dashboard_Project_SiteAdmin Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC173_Detail_Project_Dashboard_Project_SiteAdmin Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint2.TC_173_Detail_Project_Dashboard_Project_SiteAdmin.TC173_Detail_Project_Dashboard_Project_SiteAdmin(TC_173_Detail_Project_Dashboard_Project_SiteAdmin.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC173_Detail_Project_Dashboard_Project_SiteAdmin -->
  <testcase name="TC65_Verify_Setting_Version_Approve" time="248.615" classname="com.desktopWeb.scripts.setting.TC_65_Verify_Setting_Version_Approve">
    <failure type="java.lang.AssertionError" message="Step TC65_Verify_Setting_Version_Approve Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC65_Verify_Setting_Version_Approve Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.setting.TC_65_Verify_Setting_Version_Approve.TC65_Verify_Setting_Version_Approve(TC_65_Verify_Setting_Version_Approve.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC65_Verify_Setting_Version_Approve -->
  <testcase name="TC152_Verify_Page_News_Page_Version_Approve_Cm" time="391.071" classname="com.desktopWeb.scripts.sprint1.TC_157_Verify_Page_News_Page_Version_Approve_Cm">
    <failure type="java.lang.AssertionError" message="Step TC152_Verify_Page_News_Page_Version_Approve_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC152_Verify_Page_News_Page_Version_Approve_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_157_Verify_Page_News_Page_Version_Approve_Cm.TC152_Verify_Page_News_Page_Version_Approve_Cm(TC_157_Verify_Page_News_Page_Version_Approve_Cm.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC152_Verify_Page_News_Page_Version_Approve_Cm -->
  <testcase name="TC172_Detail_Project_Dashboard_Project_Pa" time="246.083" classname="com.desktopWeb.scripts.sprint2.TC_172_Detail_Project_Dashboard_Project_Pa">
    <failure type="java.lang.AssertionError" message="Step TC172_Detail_Project_Dashboard_Project_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC172_Detail_Project_Dashboard_Project_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint2.TC_172_Detail_Project_Dashboard_Project_Pa.TC172_Detail_Project_Dashboard_Project_Pa(TC_172_Detail_Project_Dashboard_Project_Pa.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC172_Detail_Project_Dashboard_Project_Pa -->
  <testcase name="TC80_Verify_Site_Sub_Page_Mobile_Preview" time="127.929" classname="com.desktopWeb.scripts.page.TC_80_Verify_Site_Sub_Page_Mobile_Preview"/>
  <testcase name="TC84_Detail_Site_Sub_Page_Project" time="129.616" classname="com.desktopWeb.scripts.page.TC_84_Detail_Site_Sub_Page_Project"/>
  <testcase name="TC144_Detail_Project_Sub_Page_Project_Pa" time="267.098" classname="com.desktopWeb.scripts.sprint1.TC_144_Detail_Project_Sub_Page_Project_Pa">
    <failure type="java.lang.AssertionError" message="Step TC144_Detail_Project_Sub_Page_Project_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC144_Detail_Project_Sub_Page_Project_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_144_Detail_Project_Sub_Page_Project_Pa.TC144_Detail_Project_Sub_Page_Project_Pa(TC_144_Detail_Project_Sub_Page_Project_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC144_Detail_Project_Sub_Page_Project_Pa -->
  <testcase name="TC147_SEO_Page_News_Page_Name_En" time="205.075" classname="com.desktopWeb.scripts.sprint1.TC_147_SEO_Page_News_Page_Name_En"/>
  <testcase name="TC163_Verify_Page_News_Page_Mobile_Preview_Pa" time="134.608" classname="com.desktopWeb.scripts.sprint1.TC_163_Verify_Page_News_Page_Mobile_Preview_Pa"/>
  <testcase name="TC122_Verify_Project_Sub_Page_Version_NewPage_En" time="147.706" classname="com.desktopWeb.scripts.sprint1.TC_122_Verify_Project_Sub_Page_Version_NewPage_En">
    <failure type="java.lang.AssertionError" message="Step AssertValue  Failed with description Page Name not present in the page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AssertValue  Failed with description Page Name not present in the page expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertValue(ActionEngine.java:1288)
	at com.desktopWeb.workflows.HelperClass.newPageVersion(HelperClass.java:1198)
	at com.desktopWeb.scripts.sprint1.TC_122_Verify_Project_Sub_Page_Version_NewPage_En.TC122_Verify_Project_Sub_Page_Version_NewPage_En(TC_122_Verify_Project_Sub_Page_Version_NewPage_En.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC122_Verify_Project_Sub_Page_Version_NewPage_En -->
  <testcase name="TC87_SEO_Page_News_Page_Name" time="431.923" classname="com.desktopWeb.scripts.page.TC_87_SEO_Page_News_Page_Name">
    <failure type="java.lang.AssertionError" message="Step TC87_SEO_Page_News_Page_Name Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC87_SEO_Page_News_Page_Name Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.page.TC_87_SEO_Page_News_Page_Name.TC87_SEO_Page_News_Page_Name(TC_87_SEO_Page_News_Page_Name.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC87_SEO_Page_News_Page_Name -->
  <testcase name="TC127_Detail_Project_Sub_Page_Project_Cm" time="97.243" classname="com.desktopWeb.scripts.sprint1.TC_127_Detail_Project_Sub_Page_Project_Cm"/>
  <testcase name="TC164_Verify_Page_News_Page_Version_Approve_Pa" time="264.053" classname="com.desktopWeb.scripts.sprint1.TC_164_Verify_Page_News_Page_Version_Approve_Pa">
    <failure type="java.lang.AssertionError" message="Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTextMatching(ActionEngine.java:2353)
	at com.desktopWeb.workflows.HelperClass.approveVersion(HelperClass.java:1169)
	at com.desktopWeb.scripts.sprint1.TC_164_Verify_Page_News_Page_Version_Approve_Pa.TC164_Verify_Page_News_Page_Version_Approve_Pa(TC_164_Verify_Page_News_Page_Version_Approve_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC164_Verify_Page_News_Page_Version_Approve_Pa -->
  <testcase name="TC133_Verify_Project_Sub_Page_Mobile_Preview_Cm" time="91.939" classname="com.desktopWeb.scripts.sprint1.TC_133_Verify_Project_Sub_Page_Mobile_Preview_Cm"/>
  <testcase name="TC143_Verify_Project_Sub_Page_Version_Approve_Pa" time="267.699" classname="com.desktopWeb.scripts.sprint1.TC_143_Verify_Project_Sub_Page_Version_Approve_Pa">
    <failure type="java.lang.AssertionError" message="Step TC143_Verify_Project_Sub_Page_Version_Approve_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC143_Verify_Project_Sub_Page_Version_Approve_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_143_Verify_Project_Sub_Page_Version_Approve_Pa.TC143_Verify_Project_Sub_Page_Version_Approve_Pa(TC_143_Verify_Project_Sub_Page_Version_Approve_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC143_Verify_Project_Sub_Page_Version_Approve_Pa -->
  <testcase name="TC83_Design_Site_Sub_Page_Template" time="160.062" classname="com.desktopWeb.scripts.page.TC_83_Design_Site_Sub_Page_Template"/>
  <testcase name="TC168_Verify_Project_Sub_Page_Delete_Pa" time="65.838" classname="com.desktopWeb.scripts.sprint1.TC_168_Verify_Project_Sub_Page_Delete_Pa"/>
  <testcase name="TC123_Verify_Project_Sub_Page_Mobile_Preview_En" time="98.728" classname="com.desktopWeb.scripts.sprint1.TC_123_Verify_Project_Sub_Page_Mobile_Preview_En"/>
  <testcase name="TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa" time="268.55" classname="com.desktopWeb.scripts.sprint1.TC_137_Verify_Project_Sub_Page_Version_Duplicate_Pa">
    <failure type="java.lang.AssertionError" message="Step TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_137_Verify_Project_Sub_Page_Version_Duplicate_Pa.TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa(TC_137_Verify_Project_Sub_Page_Version_Duplicate_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa -->
  <testcase name="TC92_Verify_Page_News_Page_Version_Approve" time="199.34" classname="com.desktopWeb.scripts.page.TC_92_Verify_Page_News_Page_Version_Approve"/>
  <testcase name="TC153_Verify_Page_News_Page_Version_NewPage_En" time="239.333" classname="com.desktopWeb.scripts.sprint1.TC_153_Verify_Page_News_Page_Version_NewPage_En">
    <failure type="java.lang.AssertionError" message="Step AssertValue  Failed with description Page Name not present in the page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AssertValue  Failed with description Page Name not present in the page expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertValue(ActionEngine.java:1288)
	at com.desktopWeb.workflows.HelperClass.newPageVersion(HelperClass.java:1198)
	at com.desktopWeb.scripts.sprint1.TC_153_Verify_Page_News_Page_Version_NewPage_En.TC153_Verify_Page_News_Page_Version_NewPage_En(TC_153_Verify_Page_News_Page_Version_NewPage_En.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC153_Verify_Page_News_Page_Version_NewPage_En -->
  <testcase name="TC77_SEO_Site_Sub_Page_Name" time="137.439" classname="com.desktopWeb.scripts.page.TC_77_SEO_Site_Sub_Page_Name"/>
  <testcase name="TC91_Location_Page_News_Page_Location" time="211.676" classname="com.desktopWeb.scripts.page.TC_91_Location_Page_News_Page_Location"/>
  <testcase name="TC52_Detail_Update_Project_Desc" time="257.849" classname="com.desktopWeb.scripts.setting.TC_57_Detail_Setting_Project_Desc">
    <failure type="java.lang.AssertionError" message="Step TC52_Detail_Update_Project_Desc Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC52_Detail_Update_Project_Desc Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.setting.TC_57_Detail_Setting_Project_Desc.TC52_Detail_Update_Project_Desc(TC_57_Detail_Setting_Project_Desc.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC52_Detail_Update_Project_Desc -->
  <testcase name="TC152_Verify_Page_News_Page_Version_Approve_En" time="267.556" classname="com.desktopWeb.scripts.sprint1.TC_152_Verify_Page_News_Page_Version_Approve_En">
    <failure type="java.lang.AssertionError" message="Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTextMatching(ActionEngine.java:2353)
	at com.desktopWeb.workflows.HelperClass.approveVersion(HelperClass.java:1169)
	at com.desktopWeb.scripts.sprint1.TC_152_Verify_Page_News_Page_Version_Approve_En.TC152_Verify_Page_News_Page_Version_Approve_En(TC_152_Verify_Page_News_Page_Version_Approve_En.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC152_Verify_Page_News_Page_Version_Approve_En -->
  <testcase name="TC145_Detail_Page_News_Page_Project_En" time="390.008" classname="com.desktopWeb.scripts.sprint1.TC_145_Detail_Page_News_Page_Project_En">
    <failure type="java.lang.AssertionError" message="Step TC145_Detail_Page_News_Page_Project_En Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC145_Detail_Page_News_Page_Project_En Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_145_Detail_Page_News_Page_Project_En.TC145_Detail_Page_News_Page_Project_En(TC_145_Detail_Page_News_Page_Project_En.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC145_Detail_Page_News_Page_Project_En -->
  <testcase name="TC125_WCCP_450_Verify_View_Project_En" time="41.27" classname="com.desktopWeb.scripts.sprint1.TC_136_WCCP_450_Verify_View_Project_Pa"/>
  <testcase name="TC125_WCCP_450_Verify_View_Project_En" time="139.048" classname="com.desktopWeb.scripts.sprint1.TC_125_WCCP_450_Verify_View_Project_En"/>
  <testcase name="TC132_Location_Project_Sub_Page_Location_Cm" time="128.182" classname="com.desktopWeb.scripts.sprint1.TC_132_Location_Project_Sub_Page_Location_Cm"/>
  <testcase name="TC160_Verify_Page_News_Page_Version_NewPage_Cm" time="406.218" classname="com.desktopWeb.scripts.sprint1.TC_160_Verify_Page_News_Page_Version_NewPage_Cm">
    <failure type="java.lang.AssertionError" message="Step TC160_Verify_Page_News_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC160_Verify_Page_News_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_160_Verify_Page_News_Page_Version_NewPage_Cm.TC160_Verify_Page_News_Page_Version_NewPage_Cm(TC_160_Verify_Page_News_Page_Version_NewPage_Cm.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC160_Verify_Page_News_Page_Version_NewPage_Cm -->
  <testcase name="TC178_WCCP_418_1" time="702.471" classname="com.desktopWeb.scripts.sprint2.TC_178_WCCP_418_1">
    <failure type="java.lang.AssertionError" message="Step Click Failed with description Unable to click on Menu/Sign Out expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Click Failed with description Unable to click on Menu/Sign Out expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.click(ActionEngine.java:100)
	at com.desktopWeb.workflows.HelperClass.signOut(HelperClass.java:297)
	at com.desktopWeb.scripts.sprint2.TC_178_WCCP_418_1.TC178_WCCP_418_1(TC_178_WCCP_418_1.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC178_WCCP_418_1 -->
  <testcase name="TC142_Verify_Project_Sub_Page_Mobile_Preview_Pa" time="85.274" classname="com.desktopWeb.scripts.sprint1.TC_142_Verify_Project_Sub_Page_Mobile_Preview_Pa"/>
  <testcase name="TC162_Verify_Page_News_Page_Version_Duplicate_Pa" time="200.169" classname="com.desktopWeb.scripts.sprint1.TC_162_Verify_Page_News_Page_Version_Duplicate_Pa"/>
  <testcase name="TC67_Verify_Update_Version_Duplicate" time="80.069" classname="com.desktopWeb.scripts.addUpdate.TC_67_Verify_Update_Version_Duplicate"/>
  <testcase name="TC180_WCCP_417_414" time="569.195" classname="com.desktopWeb.scripts.sprint2.TC_180_WCCP_417_1">
    <failure type="java.lang.AssertionError" message="Step TC180_WCCP_417_414 Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC180_WCCP_417_414 Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint2.TC_180_WCCP_417_1.TC180_WCCP_417_414(TC_180_WCCP_417_1.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC180_WCCP_417_414 -->
  <testcase name="TC134_Verify_Project_Sub_Page_Version_Approve_Cm" time="313.328" classname="com.desktopWeb.scripts.sprint1.TC_134_Verify_Project_Sub_Page_Version_Approve_Cm">
    <failure type="java.lang.AssertionError" message="Step TC134_Verify_Project_Sub_Page_Version_Approve_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC134_Verify_Project_Sub_Page_Version_Approve_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_134_Verify_Project_Sub_Page_Version_Approve_Cm.TC134_Verify_Project_Sub_Page_Version_Approve_Cm(TC_134_Verify_Project_Sub_Page_Version_Approve_Cm.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC134_Verify_Project_Sub_Page_Version_Approve_Cm -->
  <testcase name="TC93_Detail_Page_News_Page_Project" time="350.699" classname="com.desktopWeb.scripts.page.TC_93_Detail_Page_News_Page_Project">
    <failure type="java.lang.AssertionError" message="Step TC93_Detail_Page_News_Page_Project Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC93_Detail_Page_News_Page_Project Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.page.TC_93_Detail_Page_News_Page_Project.TC93_Detail_Page_News_Page_Project(TC_93_Detail_Page_News_Page_Project.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC93_Detail_Page_News_Page_Project -->
  <testcase name="TC88_Verify_Page_News_Page_Version_Duplicate" time="157.376" classname="com.desktopWeb.scripts.page.TC_88_Verify_Page_News_Page_Version_Duplicate"/>
  <testcase name="TC150_Design_Page_News_Page_Template_En" time="221.57" classname="com.desktopWeb.scripts.sprint1.TC_150_Design_Page_News_Page_Template_En"/>
  <testcase name="TC135_Verify_Project_Sub_Page_Version_NewPage_Pa" time="267.327" classname="com.desktopWeb.scripts.sprint1.TC_135_Verify_Project_Sub_Page_Version_NewPage_Pa">
    <failure type="java.lang.AssertionError" message="Step TC135_Verify_Project_Sub_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC135_Verify_Project_Sub_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_135_Verify_Project_Sub_Page_Version_NewPage_Pa.TC135_Verify_Project_Sub_Page_Version_NewPage_Pa(TC_135_Verify_Project_Sub_Page_Version_NewPage_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC135_Verify_Project_Sub_Page_Version_NewPage_Pa -->
  <testcase name="TC141_Location_Project_Sub_Page_Location_Pa" time="297.238" classname="com.desktopWeb.scripts.sprint1.TC_141_Location_Project_Sub_Page_Location_Pa">
    <failure type="java.lang.AssertionError" message="Step TC141_Location_Project_Sub_Page_Location_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC141_Location_Project_Sub_Page_Location_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_141_Location_Project_Sub_Page_Location_Pa.TC141_Location_Project_Sub_Page_Location_Pa(TC_141_Location_Project_Sub_Page_Location_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC141_Location_Project_Sub_Page_Location_Pa -->
  <testcase name="TC155_Verify_Page_News_Page_Mobile_Preview_Cm" time="134.693" classname="com.desktopWeb.scripts.sprint1.TC_155_Verify_Page_News_Page_Mobile_Preview_Cm"/>
  <testcase name="TC89_Verify_Page_News_Page_Mobile_Preview" time="171.025" classname="com.desktopWeb.scripts.page.TC_89_Verify_Page_News_Page_Mobile_Preview"/>
  <testcase name="TC81_Verify_Site_Sub_Page_Delete" time="227.572" classname="com.desktopWeb.scripts.page.TC_81_Verify_Site_Sub_Page_Delete"/>
  <testcase name="TC130_Design_Project_Sub_Page_Template_Cm" time="112.309" classname="com.desktopWeb.scripts.sprint1.TC_130_Design_Project_Sub_Page_Template_Cm"/>
  <testcase name="TC161_Verify_Project_Sub_Page_Delete_Cm" time="66.428" classname="com.desktopWeb.scripts.sprint1.TC_161_Verify_Project_Sub_Page_Delete_Cm"/>
  <testcase name="TC94_Verify_Page_Sitemap_Links" time="220.604" classname="com.desktopWeb.scripts.page.TC_94_Verify_Page_Sitemap_Links">
    <failure type="java.lang.AssertionError" message="Step AsserTitle  Failed with description Page title is not matched with Engage Victoria :: Privacy Policy expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AsserTitle  Failed with description Page title is not matched with Engage Victoria :: Privacy Policy expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTitle(ActionEngine.java:1487)
	at com.desktopWeb.workflows.HelperClass.verifyPageSitemapsLinks(HelperClass.java:835)
	at com.desktopWeb.scripts.page.TC_94_Verify_Page_Sitemap_Links.TC94_Verify_Page_Sitemap_Links(TC_94_Verify_Page_Sitemap_Links.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC94_Verify_Page_Sitemap_Links -->
  <testcase name="TC90_Design_Page_News_Page_Template" time="370.744" classname="com.desktopWeb.scripts.page.TC_90_Design_Page_News_Page_Template">
    <failure type="java.lang.AssertionError" message="Step TC90_Design_Page_News_Page_Template Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC90_Design_Page_News_Page_Template Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.page.TC_90_Design_Page_News_Page_Template.TC90_Design_Page_News_Page_Template(TC_90_Design_Page_News_Page_Template.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC90_Design_Page_News_Page_Template -->
  <testcase name="TC68_Verify_Authoring_Update_Options" time="53.56" classname="com.desktopWeb.scripts.addUpdate.TC_68_Verify_Authoring_Update_Options"/>
  <testcase name="TC66_Verify_Setting_Version_Duplicate" time="67.601" classname="com.desktopWeb.scripts.setting.TC_66_Verify_Setting_Version_Duplicate"/>
  <testcase name="TC149_Verify_Page_News_Page_Mobile_Preview_En" time="140.981" classname="com.desktopWeb.scripts.sprint1.TC_149_Verify_Page_News_Page_Mobile_Preview_En"/>
  <testcase name="TC158_Location_Page_News_Page_Location_Cm" time="216.888" classname="com.desktopWeb.scripts.sprint1.TC_158_Location_Page_News_Page_Location_Cm"/>
  <testcase name="TC146_Verify_Page_News_Page_Delete_En" time="120.038" classname="com.desktopWeb.scripts.sprint1.TC_146_Verify_Page_News_Page_Delete_En"/>
  <testcase name="TC169_Detail_Page_News_Page_Project_Pa" time="407.676" classname="com.desktopWeb.scripts.sprint1.TC_169_Detail_Page_News_Page_Project_Pa">
    <failure type="java.lang.AssertionError" message="Step TC169_Detail_Page_News_Page_Project_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC169_Detail_Page_News_Page_Project_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_169_Detail_Page_News_Page_Project_Pa.TC169_Detail_Page_News_Page_Project_Pa(TC_169_Detail_Page_News_Page_Project_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC169_Detail_Page_News_Page_Project_Pa -->
  <testcase name="TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm" time="307.803" classname="com.desktopWeb.scripts.sprint1.TC_128_Verify_Project_Sub_Page_Version_Duplicate_Cm">
    <failure type="java.lang.AssertionError" message="Step TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_128_Verify_Project_Sub_Page_Version_Duplicate_Cm.TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm(TC_128_Verify_Project_Sub_Page_Version_Duplicate_Cm.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm -->
  <testcase name="TC159_Detail_Page_News_Page_Project_Cm" time="192.722" classname="com.desktopWeb.scripts.sprint1.TC_159_Detail_Page_News_Page_Project_Cm"/>
  <testcase name="TC78_Verify_Site_Sub_Page_Version_Duplicate" time="112.23" classname="com.desktopWeb.scripts.page.TC_78_Verify_Site_Sub_Page_Version_Duplicate"/>
  <testcase name="TC179_WCCP_418_2" time="436.469" classname="com.desktopWeb.scripts.sprint2.TC_179_WCCP_418_2">
    <failure type="java.lang.AssertionError" message="Step Select  Failed with description Automation Project - LwUX is Not Select from the DropDown Page Location expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Select  Failed with description Automation Project - LwUX is Not Select from the DropDown Page Location expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.selectByVisibleText(ActionEngine.java:907)
	at com.desktopWeb.workflows.HelperClass.createSubPage(HelperClass.java:1981)
	at com.desktopWeb.scripts.sprint2.TC_179_WCCP_418_2.TC179_WCCP_418_2(TC_179_WCCP_418_2.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC179_WCCP_418_2 -->
  <testcase name="TC151_Location_Page_News_Page_Location_En" time="306.118" classname="com.desktopWeb.scripts.sprint1.TC_151_Location_Page_News_Page_Location_En"/>
  <testcase name="TC126_Verify_Project_Sub_Page_Version_NewPage_Cm" time="306.85" classname="com.desktopWeb.scripts.sprint1.TC_126_Verify_Project_Sub_Page_Version_NewPage_Cm">
    <failure type="java.lang.AssertionError" message="Step TC126_Verify_Project_Sub_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC126_Verify_Project_Sub_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_126_Verify_Project_Sub_Page_Version_NewPage_Cm.TC126_Verify_Project_Sub_Page_Version_NewPage_Cm(TC_126_Verify_Project_Sub_Page_Version_NewPage_Cm.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC126_Verify_Project_Sub_Page_Version_NewPage_Cm -->
  <testcase name="TC131_SEO_Project_Sub_Page_Name_Cm" time="102.309" classname="com.desktopWeb.scripts.sprint1.TC_131_SEO_Project_Sub_Page_Name_Cm"/>
  <testcase name="TC84_Detail_Site_Sub_Page_Project" time="330.556" classname="com.desktopWeb.scripts.page.TC_85_Create_New_Project_Page_New_Project"/>
  <testcase name="TC154_Verify_Page_News_Page_Version_Duplicate_Cm" time="366.903" classname="com.desktopWeb.scripts.sprint1.TC_154_Verify_Page_News_Page_Version_Duplicate_Cm">
    <failure type="java.lang.AssertionError" message="Step TC154_Verify_Page_News_Page_Version_Duplicate_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC154_Verify_Page_News_Page_Version_Duplicate_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_154_Verify_Page_News_Page_Version_Duplicate_Cm.TC154_Verify_Page_News_Page_Version_Duplicate_Cm(TC_154_Verify_Page_News_Page_Version_Duplicate_Cm.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC154_Verify_Page_News_Page_Version_Duplicate_Cm -->
  <testcase name="TC165_Location_Page_News_Page_Location_Pa" time="392.384" classname="com.desktopWeb.scripts.sprint1.TC_165_Location_Page_News_Page_Location_Pa">
    <failure type="java.lang.AssertionError" message="Step TC165_Location_Page_News_Page_Location_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC165_Location_Page_News_Page_Location_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_165_Location_Page_News_Page_Location_Pa.TC165_Location_Page_News_Page_Location_Pa(TC_165_Location_Page_News_Page_Location_Pa.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC165_Location_Page_News_Page_Location_Pa -->
</testsuite> <!-- Grouping(failed) -->
