<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HW1315" name="Grouping(failed)(failed)" tests="102" failures="46" timestamp="4 Feb 2017 02:15:00 GMT" time="23797.845" errors="0">
  <testcase name="TC141_Location_Project_Sub_Page_Location_Pa" time="330.959" classname="com.desktopWeb.scripts.sprint1.TC_141_Location_Project_Sub_Page_Location_Pa">
    <failure type="java.lang.AssertionError" message="Step TC141_Location_Project_Sub_Page_Location_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC141_Location_Project_Sub_Page_Location_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_141_Location_Project_Sub_Page_Location_Pa.TC141_Location_Project_Sub_Page_Location_Pa(TC_141_Location_Project_Sub_Page_Location_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC141_Location_Project_Sub_Page_Location_Pa -->
  <testcase name="TC101_Verify_Dashboard_Moderation_Recently_ApprovetoApprove" time="89.313" classname="com.desktopWeb.scripts.dashboard.TC_101_Verify_Dashboard_Moderation_Recently_ApprovetoApprove"/>
  <testcase name="TC102_Verify_Dashboard_Moderation_Recently_RejecttoApprove" time="95.89" classname="com.desktopWeb.scripts.dashboard.TC_102_Verify_Dashboard_Moderation_Recently_RejecttoApprove"/>
  <testcase name="TC104_Verify_Dashboard_Moderation_Recently_RejecttoRefer" time="88.561" classname="com.desktopWeb.scripts.dashboard.TC_104_Verify_Dashboard_Moderation_Recently_RejecttoRefer"/>
  <testcase name="TC105_Verify_Dashboard_Moderation_Refer_Approve" time="101.535" classname="com.desktopWeb.scripts.dashboard.TC_105_Verify_Dashboard_Moderation_Refer_Approve">
    <failure type="java.lang.AssertionError" message="Step AssertText  Failed with description APPROVED is not present in the element  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AssertText  Failed with description APPROVED is not present in the element  expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertText(ActionEngine.java:1392)
	at com.desktopWeb.workflows.HelperClass.approveReviewComment(HelperClass.java:2103)
	at com.desktopWeb.scripts.dashboard.TC_105_Verify_Dashboard_Moderation_Refer_Approve.TC105_Verify_Dashboard_Moderation_Refer_Approve(TC_105_Verify_Dashboard_Moderation_Refer_Approve.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC105_Verify_Dashboard_Moderation_Refer_Approve -->
  <testcase name="TC106_Verify_Dashboard_Moderation_Refer_Reject" time="115.789" classname="com.desktopWeb.scripts.dashboard.TC_106_Verify_Dashboard_Moderation_Refer_Reject"/>
  <testcase name="TC109_Verify_Dashboard_Create_Site_User_SiteAdmin" time="232.022" classname="com.desktopWeb.scripts.dashboard.TC_109_Verify_Dashboard_Create_Site_User_SiteAdmin">
    <failure type="java.lang.AssertionError" message="Step TC109_Verify_Dashboard_Create_Site_User_SiteAdmin Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC109_Verify_Dashboard_Create_Site_User_SiteAdmin Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.dashboard.TC_109_Verify_Dashboard_Create_Site_User_SiteAdmin.TC109_Verify_Dashboard_Create_Site_User_SiteAdmin(TC_109_Verify_Dashboard_Create_Site_User_SiteAdmin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC109_Verify_Dashboard_Create_Site_User_SiteAdmin -->
  <testcase name="TC110_Verify_Dashboard_Create_Community_User" time="113.2" classname="com.desktopWeb.scripts.dashboard.TC_110_Verify_Dashboard_Create_Community_User"/>
  <testcase name="TC111_Verify_DashBoard_Sitemap_Links" time="712.095" classname="com.desktopWeb.scripts.dashboard.TC_111_Verify_DashBoard_Sitemap_Links">
    <failure type="java.lang.AssertionError" message="Step TC111_Verify_DashBoard_Sitemap_Links Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC111_Verify_DashBoard_Sitemap_Links Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.dashboard.TC_111_Verify_DashBoard_Sitemap_Links.TC111_Verify_DashBoard_Sitemap_Links(TC_111_Verify_DashBoard_Sitemap_Links.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC111_Verify_DashBoard_Sitemap_Links -->
  <testcase name="TC112_Verify_DashBoard_HiveSetting_Moderation_Method_Add_Delete" time="58.801" classname="com.desktopWeb.scripts.dashboard.TC_112_Verify_DashBoard_HiveSetting_Moderation_Method_Add_Delete"/>
  <testcase name="TC95_Verify_Authoring_Dashboard_Options" time="75.741" classname="com.desktopWeb.scripts.dashboard.TC_95_Verify_Authoring_Dashboard_Options"/>
  <testcase name="TC97_Verify_Dashboard_Moderation_Awaiting_Reject" time="126.851" classname="com.desktopWeb.scripts.dashboard.TC_97_Verify_Dashboard_Moderation_Awaiting_Reject"/>
  <testcase name="TC99_Verify_Dashboard_Moderation_Recently_ApprovetoRefer" time="85.372" classname="com.desktopWeb.scripts.dashboard.TC_99_Verify_Dashboard_Moderation_Recently_ApprovetoRefer"/>
  <testcase name="TC41_Add_FAQ" time="147.048" classname="com.desktopWeb.scripts.tools.TC_41_Add_FAQ"/>
  <testcase name="TC42_Add_Key_Dates" time="155.899" classname="com.desktopWeb.scripts.tools.TC_42_Add_Key_Dates"/>
  <testcase name="TC43_Add_Links" time="321.185" classname="com.desktopWeb.scripts.tools.TC_43_Add_Links"/>
  <testcase name="TC45_Add_Contact_us" time="230.413" classname="com.desktopWeb.scripts.tools.TC_45_Add_Contact_us"/>
  <testcase name="TC46_Add_News_Feed" time="187.034" classname="com.desktopWeb.scripts.tools.TC_46_Add_News_Feed"/>
  <testcase name="TC47_Add_Feature" time="211.806" classname="com.desktopWeb.scripts.tools.TC_47_Add_Feature">
    <failure type="java.lang.AssertionError" message="Step Click Failed with description Unable to click on Save Page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Click Failed with description Unable to click on Save Page expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.click(ActionEngine.java:100)
	at com.desktopWeb.workflows.HelperClass.savePage(HelperClass.java:2188)
	at com.desktopWeb.workflows.HelperClass.addFeature(HelperClass.java:1835)
	at com.desktopWeb.scripts.tools.TC_47_Add_Feature.TC47_Add_Feature(TC_47_Add_Feature.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC47_Add_Feature -->
  <testcase name="TC48_Add_Accodion" time="265.578" classname="com.desktopWeb.scripts.tools.TC_48_Add_Accodion"/>
  <testcase name="TC50_Verify_Authoring_Tools_Options" time="54.122" classname="com.desktopWeb.scripts.tools.TC_50_Verify_Authoring_Tools_Options"/>
  <testcase name="TC65_Verify_Setting_Version_Approve" time="83.767" classname="com.desktopWeb.scripts.setting.TC_65_Verify_Setting_Version_Approve">
    <failure type="java.lang.AssertionError" message="Step AsserTitle  Failed with description Page title is not matched with Engage Victoria :: New Project for Test Execution expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AsserTitle  Failed with description Page title is not matched with Engage Victoria :: New Project for Test Execution expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTitle(ActionEngine.java:1487)
	at com.desktopWeb.workflows.HelperClass.navigateConsultation(HelperClass.java:410)
	at com.desktopWeb.scripts.setting.TC_65_Verify_Setting_Version_Approve.TC65_Verify_Setting_Version_Approve(TC_65_Verify_Setting_Version_Approve.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC65_Verify_Setting_Version_Approve -->
  <testcase name="TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa" time="259.103" classname="com.desktopWeb.scripts.sprint1.TC_137_Verify_Project_Sub_Page_Version_Duplicate_Pa">
    <failure type="java.lang.AssertionError" message="Step TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_137_Verify_Project_Sub_Page_Version_Duplicate_Pa.TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa(TC_137_Verify_Project_Sub_Page_Version_Duplicate_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC137_Verify_Project_Sub_Page_Version_Duplicate_Pa -->
  <testcase name="TC140_SEO_Project_Sub_Page_Name_Pa" time="311.779" classname="com.desktopWeb.scripts.sprint1.TC_140_SEO_Project_Sub_Page_Name_Pa">
    <failure type="java.lang.AssertionError" message="Step TC140_SEO_Project_Sub_Page_Name_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC140_SEO_Project_Sub_Page_Name_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_140_SEO_Project_Sub_Page_Name_Pa.TC140_SEO_Project_Sub_Page_Name_Pa(TC_140_SEO_Project_Sub_Page_Name_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC140_SEO_Project_Sub_Page_Name_Pa -->
  <testcase name="TC179_WCCP_418_2" time="432.375" classname="com.desktopWeb.scripts.sprint2.TC_179_WCCP_418_2">
    <failure type="java.lang.AssertionError" message="Step Select  Failed with description Automation Project - IGaO is Not Select from the DropDown Page Location expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Select  Failed with description Automation Project - IGaO is Not Select from the DropDown Page Location expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.selectByVisibleText(ActionEngine.java:907)
	at com.desktopWeb.workflows.HelperClass.createSubPage(HelperClass.java:1994)
	at com.desktopWeb.scripts.sprint2.TC_179_WCCP_418_2.TC179_WCCP_418_2(TC_179_WCCP_418_2.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC179_WCCP_418_2 -->
  <testcase name="TC126_Verify_Project_Sub_Page_Version_NewPage_Cm" time="297.86" classname="com.desktopWeb.scripts.sprint1.TC_126_Verify_Project_Sub_Page_Version_NewPage_Cm">
    <failure type="java.lang.AssertionError" message="Step TC126_Verify_Project_Sub_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC126_Verify_Project_Sub_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_126_Verify_Project_Sub_Page_Version_NewPage_Cm.TC126_Verify_Project_Sub_Page_Version_NewPage_Cm(TC_126_Verify_Project_Sub_Page_Version_NewPage_Cm.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC126_Verify_Project_Sub_Page_Version_NewPage_Cm -->
  <testcase name="TC145_Detail_Page_News_Page_Project_En" time="193.495" classname="com.desktopWeb.scripts.sprint1.TC_145_Detail_Page_News_Page_Project_En"/>
  <testcase name="TC167_Verify_Page_News_Page_Version_NewPage_Pa" time="361.311" classname="com.desktopWeb.scripts.sprint1.TC_167_Verify_Page_News_Page_Version_NewPage_Pa">
    <failure type="java.lang.AssertionError" message="Step TC167_Verify_Page_News_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC167_Verify_Page_News_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_167_Verify_Page_News_Page_Version_NewPage_Pa.TC167_Verify_Page_News_Page_Version_NewPage_Pa(TC_167_Verify_Page_News_Page_Version_NewPage_Pa.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC167_Verify_Page_News_Page_Version_NewPage_Pa -->
  <testcase name="TC160_Verify_Page_News_Page_Version_NewPage_Cm" time="395.381" classname="com.desktopWeb.scripts.sprint1.TC_160_Verify_Page_News_Page_Version_NewPage_Cm">
    <failure type="java.lang.AssertionError" message="Step TC160_Verify_Page_News_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC160_Verify_Page_News_Page_Version_NewPage_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_160_Verify_Page_News_Page_Version_NewPage_Cm.TC160_Verify_Page_News_Page_Version_NewPage_Cm(TC_160_Verify_Page_News_Page_Version_NewPage_Cm.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC160_Verify_Page_News_Page_Version_NewPage_Cm -->
  <testcase name="TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm" time="302.088" classname="com.desktopWeb.scripts.sprint1.TC_128_Verify_Project_Sub_Page_Version_Duplicate_Cm">
    <failure type="java.lang.AssertionError" message="Step TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_128_Verify_Project_Sub_Page_Version_Duplicate_Cm.TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm(TC_128_Verify_Project_Sub_Page_Version_Duplicate_Cm.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC128_Verify_Project_Sub_Page_Version_Duplicate_Cm -->
  <testcase name="TC169_Detail_Page_News_Page_Project_Pa" time="397.522" classname="com.desktopWeb.scripts.sprint1.TC_169_Detail_Page_News_Page_Project_Pa">
    <failure type="java.lang.AssertionError" message="Step TC169_Detail_Page_News_Page_Project_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC169_Detail_Page_News_Page_Project_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_169_Detail_Page_News_Page_Project_Pa.TC169_Detail_Page_News_Page_Project_Pa(TC_169_Detail_Page_News_Page_Project_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC169_Detail_Page_News_Page_Project_Pa -->
  <testcase name="TC144_Detail_Project_Sub_Page_Project_Pa" time="256.576" classname="com.desktopWeb.scripts.sprint1.TC_144_Detail_Project_Sub_Page_Project_Pa">
    <failure type="java.lang.AssertionError" message="Step TC144_Detail_Project_Sub_Page_Project_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC144_Detail_Project_Sub_Page_Project_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_144_Detail_Project_Sub_Page_Project_Pa.TC144_Detail_Project_Sub_Page_Project_Pa(TC_144_Detail_Project_Sub_Page_Project_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC144_Detail_Project_Sub_Page_Project_Pa -->
  <testcase name="TC154_Verify_Page_News_Page_Version_Duplicate_Cm" time="202.28" classname="com.desktopWeb.scripts.sprint1.TC_154_Verify_Page_News_Page_Version_Duplicate_Cm"/>
  <testcase name="TC49_Verify_Authoring_tools_Edit_Banner" time="251.661" classname="com.desktopWeb.scripts.edit.TC_49_Verify_Authoring_Edit_Banner">
    <failure type="java.lang.AssertionError" message="Step TC49_Verify_Authoring_tools_Edit_Banner Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC49_Verify_Authoring_tools_Edit_Banner Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.edit.TC_49_Verify_Authoring_Edit_Banner.TC49_Verify_Authoring_tools_Edit_Banner(TC_49_Verify_Authoring_Edit_Banner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC49_Verify_Authoring_tools_Edit_Banner -->
  <testcase name="TC20_Add_HTML" time="257.552" classname="com.desktopWeb.scripts.tools.TC_20_Add_HTML">
    <failure type="java.lang.AssertionError" message="Step TC_20_Add_HTML Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC_20_Add_HTML Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.tools.TC_20_Add_HTML.TC20_Add_HTML(TC_20_Add_HTML.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC20_Add_HTML -->
  <testcase name="TC21_Add_Block_Quote" time="156.139" classname="com.desktopWeb.scripts.tools.TC_21_Add_Block_Quote"/>
  <testcase name="TC23_Add_Divider" time="153.571" classname="com.desktopWeb.scripts.tools.TC_23_Add_Divider"/>
  <testcase name="TC24_Add_Image" time="261.582" classname="com.desktopWeb.scripts.tools.TC_24_Add_Image"/>
  <testcase name="TC25_Add_Flexi" time="152.388" classname="com.desktopWeb.scripts.tools.TC_25_Add_Flexi"/>
  <testcase name="TC28_Add_Web_Map" time="181.049" classname="com.desktopWeb.scripts.tools.TC_28_Add_Web_Map"/>
  <testcase name="TC29_Add_Image_Gallary" time="309.56" classname="com.desktopWeb.scripts.tools.TC_29_Add_Image_Gallary">
    <failure type="java.lang.AssertionError" message="Step TC29_Add_Image_Gallary Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC29_Add_Image_Gallary Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.tools.TC_29_Add_Image_Gallary.TC29_Add_Image_Gallary(TC_29_Add_Image_Gallary.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC29_Add_Image_Gallary -->
  <testcase name="TC30_Add_Image_Slider" time="309.702" classname="com.desktopWeb.scripts.tools.TC_30_Add_Image_Slider">
    <failure type="java.lang.AssertionError" message="Step TC30_Add_Image_Slider Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC30_Add_Image_Slider Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.tools.TC_30_Add_Image_Slider.TC30_Add_Image_Slider(TC_30_Add_Image_Slider.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC30_Add_Image_Slider -->
  <testcase name="TC31_Add_Video" time="170.422" classname="com.desktopWeb.scripts.tools.TC_31_Add_Video"/>
  <testcase name="TC33_Add_Form" time="182.185" classname="com.desktopWeb.scripts.tools.TC_33_Add_Form"/>
  <testcase name="TC35_Add_Conversation" time="135.095" classname="com.desktopWeb.scripts.tools.TC_35_Add_Conversation"/>
  <testcase name="TC37_Add_Visioner_Input" time="102.853" classname="com.desktopWeb.scripts.tools.TC_37_Add_Visioner_Input">
    <failure type="java.lang.AssertionError" message="Step Click Failed with description Unable to click on Main Area expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Click Failed with description Unable to click on Main Area expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.click(ActionEngine.java:100)
	at com.desktopWeb.workflows.HelperClass.openTools(HelperClass.java:1883)
	at com.desktopWeb.workflows.HelperClass.addVisionerInput(HelperClass.java:1626)
	at com.desktopWeb.scripts.tools.TC_37_Add_Visioner_Input.TC37_Add_Visioner_Input(TC_37_Add_Visioner_Input.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC37_Add_Visioner_Input -->
  <testcase name="TC143_Verify_Project_Sub_Page_Version_Approve_Pa" time="260.273" classname="com.desktopWeb.scripts.sprint1.TC_143_Verify_Project_Sub_Page_Version_Approve_Pa">
    <failure type="java.lang.AssertionError" message="Step TC143_Verify_Project_Sub_Page_Version_Approve_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC143_Verify_Project_Sub_Page_Version_Approve_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_143_Verify_Project_Sub_Page_Version_Approve_Pa.TC143_Verify_Project_Sub_Page_Version_Approve_Pa(TC_143_Verify_Project_Sub_Page_Version_Approve_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC143_Verify_Project_Sub_Page_Version_Approve_Pa -->
  <testcase name="TC173_Detail_Project_Dashboard_Project_SiteAdmin" time="92.494" classname="com.desktopWeb.scripts.sprint2.TC_173_Detail_Project_Dashboard_Project_SiteAdmin"/>
  <testcase name="TC134_Verify_Project_Sub_Page_Version_Approve_Cm" time="301.437" classname="com.desktopWeb.scripts.sprint1.TC_134_Verify_Project_Sub_Page_Version_Approve_Cm">
    <failure type="java.lang.AssertionError" message="Step TC134_Verify_Project_Sub_Page_Version_Approve_Cm Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC134_Verify_Project_Sub_Page_Version_Approve_Cm Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_134_Verify_Project_Sub_Page_Version_Approve_Cm.TC134_Verify_Project_Sub_Page_Version_Approve_Cm(TC_134_Verify_Project_Sub_Page_Version_Approve_Cm.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC134_Verify_Project_Sub_Page_Version_Approve_Cm -->
  <testcase name="TC93_Detail_Page_News_Page_Project" time="343.807" classname="com.desktopWeb.scripts.page.TC_93_Detail_Page_News_Page_Project">
    <failure type="java.lang.AssertionError" message="Step TC93_Detail_Page_News_Page_Project Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC93_Detail_Page_News_Page_Project Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.page.TC_93_Detail_Page_News_Page_Project.TC93_Detail_Page_News_Page_Project(TC_93_Detail_Page_News_Page_Project.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC93_Detail_Page_News_Page_Project -->
  <testcase name="TC139_Design_Project_Sub_Page_Template_Pa" time="322.009" classname="com.desktopWeb.scripts.sprint1.TC_139_Design_Project_Sub_Page_Template_Pa">
    <failure type="java.lang.AssertionError" message="Step TC139_Design_Project_Sub_Page_Template_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC139_Design_Project_Sub_Page_Template_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_139_Design_Project_Sub_Page_Template_Pa.TC139_Design_Project_Sub_Page_Template_Pa(TC_139_Design_Project_Sub_Page_Template_Pa.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC139_Design_Project_Sub_Page_Template_Pa -->
  <testcase name="TC152_Verify_Page_News_Page_Version_Approve_En" time="278.524" classname="com.desktopWeb.scripts.sprint1.TC_152_Verify_Page_News_Page_Version_Approve_En">
    <failure type="java.lang.AssertionError" message="Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTextMatching(ActionEngine.java:2353)
	at com.desktopWeb.workflows.HelperClass.approveVersion(HelperClass.java:1182)
	at com.desktopWeb.scripts.sprint1.TC_152_Verify_Page_News_Page_Version_Approve_En.TC152_Verify_Page_News_Page_Version_Approve_En(TC_152_Verify_Page_News_Page_Version_Approve_En.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC152_Verify_Page_News_Page_Version_Approve_En -->
  <testcase name="TC178_WCCP_418_1" time="386.993" classname="com.desktopWeb.scripts.sprint2.TC_178_WCCP_418_1">
    <failure type="java.lang.AssertionError" message="Step TC178_WCCP_418_1 Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC178_WCCP_418_1 Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint2.TC_178_WCCP_418_1.TC178_WCCP_418_1(TC_178_WCCP_418_1.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC178_WCCP_418_1 -->
  <testcase name="TC100_Verify_Dashboard_Moderation_Recently_ApprovetoReject" time="99.543" classname="com.desktopWeb.scripts.dashboard.TC_100_Verify_Dashboard_Moderation_Recently_ApprovetoReject"/>
  <testcase name="TC02_CommonChecks_HomePage_HambergerMenu_Login_Signout_CommunityUser" time="105.18" classname="com.desktopWeb.scripts.common.TC_02_CommonChecks_HomePage_HamburgerMenu_Login_Signout_CommunityUser">
    <failure type="java.lang.AssertionError" message="Step Verify web element is display Failed with description Sign Out is not displaying expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Verify web element is display Failed with description Sign Out is not displaying expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.isElementDisplayed(ActionEngine.java:2399)
	at com.desktopWeb.workflows.HelperClass.verifyHamberger(HelperClass.java:96)
	at com.desktopWeb.scripts.common.TC_02_CommonChecks_HomePage_HamburgerMenu_Login_Signout_CommunityUser.TC02_CommonChecks_HomePage_HambergerMenu_Login_Signout_CommunityUser(TC_02_CommonChecks_HomePage_HamburgerMenu_Login_Signout_CommunityUser.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC02_CommonChecks_HomePage_HambergerMenu_Login_Signout_CommunityUser -->
  <testcase name="TC03_CommonChecks_HomePage_HambergerMenu_Login_Signout_GuestUser" time="235.697" classname="com.desktopWeb.scripts.common.TC_03_CommonChecks_HomePage_HamburgerMenu_Login_Signout_GuestUser"/>
  <testcase name="TC05_loginviaFooter_CommonCheck_FooterLinks_SearchSite_SiteAdmin" time="35.17" classname="com.desktopWeb.scripts.common.TC_05_loginviaFooter_CommonCheck_FooterLinks_SearchSite_SiteAdmin">
    <failure type="java.lang.AssertionError" message="Step Click Failed with description Unable to click on Menu/Consultation expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Click Failed with description Unable to click on Menu/Consultation expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.click(ActionEngine.java:100)
	at com.desktopWeb.workflows.HelperClass.searchConsultation(HelperClass.java:446)
	at com.desktopWeb.scripts.common.TC_05_loginviaFooter_CommonCheck_FooterLinks_SearchSite_SiteAdmin.TC05_loginviaFooter_CommonCheck_FooterLinks_SearchSite_SiteAdmin(TC_05_loginviaFooter_CommonCheck_FooterLinks_SearchSite_SiteAdmin.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC05_loginviaFooter_CommonCheck_FooterLinks_SearchSite_SiteAdmin -->
  <testcase name="TC06_loginviaFooter_CommonCheck_FooterLinks_SearchSite_CommunityUser" time="28.913" classname="com.desktopWeb.scripts.common.TC_06_loginviaFooter_CommonCheck_FooterLinks_SearchSite_CommunityUser">
    <failure type="java.lang.AssertionError" message="Step Click Failed with description Unable to click on Menu/Consultation expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Click Failed with description Unable to click on Menu/Consultation expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.click(ActionEngine.java:100)
	at com.desktopWeb.workflows.HelperClass.searchConsultation(HelperClass.java:446)
	at com.desktopWeb.scripts.common.TC_06_loginviaFooter_CommonCheck_FooterLinks_SearchSite_CommunityUser.TC06_loginviaFooter_CommonCheck_FooterLinks_SearchSite_CommunityUser(TC_06_loginviaFooter_CommonCheck_FooterLinks_SearchSite_CommunityUser.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC06_loginviaFooter_CommonCheck_FooterLinks_SearchSite_CommunityUser -->
  <testcase name="TC07_loginviaFooter_CommonCheck_FooterLinks_SearchSite_GuestUSer" time="316.67" classname="com.desktopWeb.scripts.common.TC_07_loginviaFooter_CommonCheck_FooterLinks_SearchSite_GuestUSer">
    <failure type="java.lang.AssertionError" message="Step AsserTitle  Failed with description Page title is not matched with Victorian Government expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AsserTitle  Failed with description Page title is not matched with Victorian Government expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTitle(ActionEngine.java:1487)
	at com.desktopWeb.workflows.HelperClass.verifyFooterLinks(HelperClass.java:354)
	at com.desktopWeb.scripts.common.TC_07_loginviaFooter_CommonCheck_FooterLinks_SearchSite_GuestUSer.TC07_loginviaFooter_CommonCheck_FooterLinks_SearchSite_GuestUSer(TC_07_loginviaFooter_CommonCheck_FooterLinks_SearchSite_GuestUSer.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC07_loginviaFooter_CommonCheck_FooterLinks_SearchSite_GuestUSer -->
  <testcase name="TC10_ActiveConsultation_GuestUser" time="25.255" classname="com.desktopWeb.scripts.common.TC_10_ActiveConsultation_GuestUser"/>
  <testcase name="TC11_HelpmeFindCons_SiteAdmin" time="216.576" classname="com.desktopWeb.scripts.common.TC_11_HelpmeFindCons_SiteAdmin">
    <failure type="java.lang.AssertionError" message="Step TC11_HelpmeFindCons_SiteAdmin Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC11_HelpmeFindCons_SiteAdmin Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.common.TC_11_HelpmeFindCons_SiteAdmin.TC11_HelpmeFindCons_SiteAdmin(TC_11_HelpmeFindCons_SiteAdmin.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC11_HelpmeFindCons_SiteAdmin -->
  <testcase name="TC12_HelpmeFindCons_CommunityUser" time="209.912" classname="com.desktopWeb.scripts.common.TC_12_HelpmeFindCons_CommunityUser">
    <failure type="java.lang.AssertionError" message="Step TC12_HelpmeFindCons_CommunityUser Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC12_HelpmeFindCons_CommunityUser Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.common.TC_12_HelpmeFindCons_CommunityUser.TC12_HelpmeFindCons_CommunityUser(TC_12_HelpmeFindCons_CommunityUser.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC12_HelpmeFindCons_CommunityUser -->
  <testcase name="TC13_HelpmeFindCons_GuestUser" time="35.047" classname="com.desktopWeb.scripts.common.TC_13_HelpmeFindCons_GuestUser"/>
  <testcase name="TC15_CommonChecks_InvalidEmailIDPWD" time="10.079" classname="com.desktopWeb.scripts.common.TC_15_CommonChecks_InvalidEmailIDPWD"/>
  <testcase name="TC17_Contactus_CommunityUser" time="64.23" classname="com.desktopWeb.scripts.common.TC_17_Contactus_CommunityUser"/>
  <testcase name="TC87_SEO_Page_News_Page_Name" time="357.273" classname="com.desktopWeb.scripts.page.TC_87_SEO_Page_News_Page_Name">
    <failure type="java.lang.AssertionError" message="Step TC87_SEO_Page_News_Page_Name Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC87_SEO_Page_News_Page_Name Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.page.TC_87_SEO_Page_News_Page_Name.TC87_SEO_Page_News_Page_Name(TC_87_SEO_Page_News_Page_Name.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC87_SEO_Page_News_Page_Name -->
  <testcase name="TC44_Add_Timelines" time="291.175" classname="com.desktopWeb.scripts.tools.TC_44_Add_Timelines">
    <failure type="java.lang.AssertionError" message="Step TC44_Add_Timelines Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC44_Add_Timelines Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.tools.TC_44_Add_Timelines.TC44_Add_Timelines(TC_44_Add_Timelines.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC44_Add_Timelines -->
  <testcase name="TC153_Verify_Page_News_Page_Version_NewPage_En" time="227.045" classname="com.desktopWeb.scripts.sprint1.TC_153_Verify_Page_News_Page_Version_NewPage_En"/>
  <testcase name="TC165_Location_Page_News_Page_Location_Pa" time="430.336" classname="com.desktopWeb.scripts.sprint1.TC_165_Location_Page_News_Page_Location_Pa">
    <failure type="java.lang.AssertionError" message="Step TC165_Location_Page_News_Page_Location_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC165_Location_Page_News_Page_Location_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_165_Location_Page_News_Page_Location_Pa.TC165_Location_Page_News_Page_Location_Pa(TC_165_Location_Page_News_Page_Location_Pa.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC165_Location_Page_News_Page_Location_Pa -->
  <testcase name="TC135_Verify_Project_Sub_Page_Version_NewPage_Pa" time="257.048" classname="com.desktopWeb.scripts.sprint1.TC_135_Verify_Project_Sub_Page_Version_NewPage_Pa">
    <failure type="java.lang.AssertionError" message="Step TC135_Verify_Project_Sub_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC135_Verify_Project_Sub_Page_Version_NewPage_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_135_Verify_Project_Sub_Page_Version_NewPage_Pa.TC135_Verify_Project_Sub_Page_Version_NewPage_Pa(TC_135_Verify_Project_Sub_Page_Version_NewPage_Pa.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC135_Verify_Project_Sub_Page_Version_NewPage_Pa -->
  <testcase name="TC19_Add_Content" time="146.156" classname="com.desktopWeb.scripts.tools.TC_19_Add_Content"/>
  <testcase name="TC164_Verify_Page_News_Page_Version_Approve_Pa" time="270.772" classname="com.desktopWeb.scripts.sprint1.TC_164_Verify_Page_News_Page_Version_Approve_Pa">
    <failure type="java.lang.AssertionError" message="Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step Verify Verify text Failed with description Approved by is not present in the element expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTextMatching(ActionEngine.java:2353)
	at com.desktopWeb.workflows.HelperClass.approveVersion(HelperClass.java:1182)
	at com.desktopWeb.scripts.sprint1.TC_164_Verify_Page_News_Page_Version_Approve_Pa.TC164_Verify_Page_News_Page_Version_Approve_Pa(TC_164_Verify_Page_News_Page_Version_Approve_Pa.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC164_Verify_Page_News_Page_Version_Approve_Pa -->
  <testcase name="TC180_WCCP_417_414" time="442.618" classname="com.desktopWeb.scripts.sprint2.TC_180_WCCP_417_1">
    <failure type="java.lang.AssertionError" message="Step TC180_WCCP_417_414 Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC180_WCCP_417_414 Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint2.TC_180_WCCP_417_1.TC180_WCCP_417_414(TC_180_WCCP_417_1.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC180_WCCP_417_414 -->
  <testcase name="TC166_Design_Page_News_Page_Template_Pa" time="391.68" classname="com.desktopWeb.scripts.sprint1.TC_166_Design_Page_News_Page_Template_Pa">
    <failure type="java.lang.AssertionError" message="Step TC166_Design_Page_News_Page_Template_Pa Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC166_Design_Page_News_Page_Template_Pa Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.sprint1.TC_166_Design_Page_News_Page_Template_Pa.TC166_Design_Page_News_Page_Template_Pa(TC_166_Design_Page_News_Page_Template_Pa.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC166_Design_Page_News_Page_Template_Pa -->
  <testcase name="TC172_Detail_Project_Dashboard_Project_Pa" time="63.84" classname="com.desktopWeb.scripts.sprint2.TC_172_Detail_Project_Dashboard_Project_Pa"/>
  <testcase name="TC148_Verify_Page_News_Page_Version_Duplicate_En" time="209.888" classname="com.desktopWeb.scripts.sprint1.TC_148_Verify_Page_News_Page_Version_Duplicate_En"/>
  <testcase name="TC38_Add_Visioner_Result" time="145.766" classname="com.desktopWeb.scripts.tools.TC_38_Add_Visioner_Result"/>
  <testcase name="TC90_Design_Page_News_Page_Template" time="372.153" classname="com.desktopWeb.scripts.page.TC_90_Design_Page_News_Page_Template">
    <failure type="java.lang.AssertionError" message="Step TC90_Design_Page_News_Page_Template Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC90_Design_Page_News_Page_Template Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.page.TC_90_Design_Page_News_Page_Template.TC90_Design_Page_News_Page_Template(TC_90_Design_Page_News_Page_Template.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC90_Design_Page_News_Page_Template -->
  <testcase name="TC01_CommonChecks_HomePage_HambergerMenu_Login_Signout_SiteAdmin" time="316.196" classname="com.desktopWeb.scripts.common.TC_01_CommonChecks_HomePage_HamburgerMenu_Login_Signout_SiteAdmin"/>
  <testcase name="TC103_Verify_Dashboard_Moderation_Recently_RejecttoReject" time="84.984" classname="com.desktopWeb.scripts.dashboard.TC_103_Verify_Dashboard_Moderation_Recently_RejecttoReject"/>
  <testcase name="TC107_Create_New_Project_Dashboard_Project" time="260.38" classname="com.desktopWeb.scripts.dashboard.TC_107_Create_New_Project_Dashboard_Project"/>
  <testcase name="TC113_Verify_DashBoard_Result_Form_OpenPage" time="75.982" classname="com.desktopWeb.scripts.dashboard.TC_113_Verify_DashBoard_Result_Form_OpenPage"/>
  <testcase name="TC96_Verify_Dashboard_Moderation_Awaiting_Approve" time="75.459" classname="com.desktopWeb.scripts.dashboard.TC_96_Verify_Dashboard_Moderation_Awaiting_Approve"/>
  <testcase name="TC98_Verify_Dashboard_Moderation_Awaiting_Refer" time="80.835" classname="com.desktopWeb.scripts.dashboard.TC_98_Verify_Dashboard_Moderation_Awaiting_Refer"/>
  <testcase name="TC94_Verify_Page_Sitemap_Links" time="663.861" classname="com.desktopWeb.scripts.page.TC_94_Verify_Page_Sitemap_Links">
    <failure type="java.lang.AssertionError" message="Step AsserTitle  Failed with description Page title is not matched with Engage Victoria :: Site map expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AsserTitle  Failed with description Page title is not matched with Engage Victoria :: Site map expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertTitle(ActionEngine.java:1487)
	at com.desktopWeb.workflows.HelperClass.verifyPageSitemapsLinks(HelperClass.java:877)
	at com.desktopWeb.scripts.page.TC_94_Verify_Page_Sitemap_Links.TC94_Verify_Page_Sitemap_Links(TC_94_Verify_Page_Sitemap_Links.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC94_Verify_Page_Sitemap_Links -->
  <testcase name="TC22_Add_Heading" time="152.567" classname="com.desktopWeb.scripts.tools.TC_22_Add_Heading"/>
  <testcase name="TC26_Add_Tabs_Start" time="149.725" classname="com.desktopWeb.scripts.tools.TC_26_Add_Tabs_Start">
    <failure type="java.lang.AssertionError" message="Step AssertText  Failed with description Tabheading is not present in the element  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step AssertText  Failed with description Tabheading is not present in the element  expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.assertText(ActionEngine.java:1392)
	at com.desktopWeb.workflows.HelperClass.addTabsStart(HelperClass.java:1431)
	at com.desktopWeb.scripts.tools.TC_26_Add_Tabs_Start.TC26_Add_Tabs_Start(TC_26_Add_Tabs_Start.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC26_Add_Tabs_Start -->
  <testcase name="TC32_Add_Swipe" time="242.339" classname="com.desktopWeb.scripts.tools.TC_32_Add_Swipe"/>
  <testcase name="TC34_Add_Quick_Poll" time="291.379" classname="com.desktopWeb.scripts.tools.TC_34_Add_Quick_Poll">
    <failure type="java.lang.AssertionError" message="Step TC34_Add_Quick_Poll Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC34_Add_Quick_Poll Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.tools.TC_34_Add_Quick_Poll.TC34_Add_Quick_Poll(TC_34_Add_Quick_Poll.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC34_Add_Quick_Poll -->
  <testcase name="TC36_Add_Social_Map" time="160.874" classname="com.desktopWeb.scripts.tools.TC_36_Add_Social_Map"/>
  <testcase name="TC39_Add_Forum" time="151.186" classname="com.desktopWeb.scripts.tools.TC_39_Add_Forum"/>
  <testcase name="TC04_ForgotPwdChangePwd_SiteAdmin" time="55.769" classname="com.desktopWeb.scripts.common.TC_04_ForgotPwdChangePwd_SiteAdmin"/>
  <testcase name="TC08_ActiveConsultation_SiteAdmin" time="64.767" classname="com.desktopWeb.scripts.common.TC_08_ActiveConsultation_SiteAdmin"/>
  <testcase name="TC14_Signup_from_Menu_Footer" time="37.982" classname="com.desktopWeb.scripts.common.TC_14_Signup_from_Menu_Footer"/>
  <testcase name="TC16_Contactus_SiteAdmin" time="83.314" classname="com.desktopWeb.scripts.common.TC_16_Contactus_SiteAdmin"/>
  <testcase name="TC18_Contactus_GuestUser" time="64.686" classname="com.desktopWeb.scripts.common.TC_18_Contactus_GuestUser"/>
  <testcase name="TC122_Verify_Project_Sub_Page_Version_NewPage_En" time="133.824" classname="com.desktopWeb.scripts.sprint1.TC_122_Verify_Project_Sub_Page_Version_NewPage_En"/>
  <testcase name="TC174_Verify_Field_Enable_ToEdit_Dashoard_Project_En" time="114.607" classname="com.desktopWeb.scripts.sprint2.TC_174_Verify_Field_Enable_ToEdit_Dashoard_Project_En">
    <failure type="java.lang.AssertionError" message="Step IsEnabled  Failed with description Project Type is not Enabled expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step IsEnabled  Failed with description Project Type is not Enabled expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.ctaf.accelerators.ActionEngine.isEnabled(ActionEngine.java:1161)
	at com.desktopWeb.workflows.HelperClass.VerifyFieldsEnableToEditOnProjectPage(HelperClass.java:2344)
	at com.desktopWeb.scripts.sprint2.TC_174_Verify_Field_Enable_ToEdit_Dashoard_Project_En.TC174_Verify_Field_Enable_ToEdit_Dashoard_Project_En(TC_174_Verify_Field_Enable_ToEdit_Dashoard_Project_En.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC174_Verify_Field_Enable_ToEdit_Dashoard_Project_En -->
  <testcase name="TC40_Add_Document_Library" time="346.159" classname="com.desktopWeb.scripts.tools.TC_40_Add_Document_Library">
    <failure type="java.lang.AssertionError" message="Step TC40_Add_Document_Library Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC40_Add_Document_Library Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.tools.TC_40_Add_Document_Library.TC40_Add_Document_Library(TC_40_Add_Document_Library.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC40_Add_Document_Library -->
  <testcase name="TC108_Verify_Dashboard_Create_Site_User" time="229.315" classname="com.desktopWeb.scripts.dashboard.TC_108_Verify_Dashboard_Create_Site_User">
    <failure type="java.lang.AssertionError" message="Step TC108_Verify_Dashboard_Create_Site_User Failed with description Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step TC108_Verify_Dashboard_Create_Site_User Failed with description Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:778)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:91)
	at com.desktopWeb.scripts.dashboard.TC_108_Verify_Dashboard_Create_Site_User.TC108_Verify_Dashboard_Create_Site_User(TC_108_Verify_Dashboard_Create_Site_User.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC108_Verify_Dashboard_Create_Site_User -->
  <testcase name="TC27_Add_Button" time="147.096" classname="com.desktopWeb.scripts.tools.TC_27_Add_Button"/>
  <testcase name="TC09_ActiveConsultation_CommunityUser" time="38.016" classname="com.desktopWeb.scripts.common.TC_09_ActiveConsultation_CommunityUser"/>
</testsuite> <!-- Grouping(failed)(failed) -->
